# Generated by GPT-5-Codex for Journals KE
from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                ("chief_editor", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("issn_print", models.CharField(blank=True, max_length=32)),
                ("issn_online", models.CharField(blank=True, max_length=32)),
                ("language", models.CharField(blank=True, max_length=128)),
                ("country", models.CharField(blank=True, max_length=128)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
    ]
