# Generated by Django 5.2.8 on 2025-12-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journal'),
        ('api', '0002_rename_api_usertok_token_b5f09c_idx_api_usertok_token_e30abd_idx_and_more'),
    ]

    operations = [
    ]
