# Generated by Django 5.2.8 on 2025-12-02 20:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_merge_20251202_1857"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(editable=False, max_length=512, unique=True)),
                ("creator", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("contributor", models.CharField(blank=True, max_length=255)),
                (
                    "issued",
                    models.DateField(
                        blank=True, help_text="Date the publication was made available.", null=True),
                ),
                ("resource_type", models.CharField(blank=True, max_length=128)),
                ("resource_format", models.CharField(blank=True, max_length=128)),
                ("identifier", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=64)),
                ("relation", models.CharField(blank=True, max_length=255)),
                ("coverage", models.CharField(blank=True, max_length=255)),
                ("rights", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["slug"], name="api_publicati_slug_8f026f_idx"),
        ),
    ]
