# Generated by Django 5.2.8 on 2025-12-11 14:32

import json
from django.db import migrations, models


MULTI_FIELDS = (
    "creator",
    "subject",
    "contributor",
    "identifier",
    "source",
    "language",
    "relation",
    "coverage",
)


def ensure_json_lists(apps, schema_editor):
    Publication = apps.get_model("api", "Publication")
    for publication in Publication.objects.all():
        updates = {}
        for field in MULTI_FIELDS:
            value = getattr(publication, field)
            if value in (None, ""):
                updates[field] = json.dumps([])
                continue
            if isinstance(value, str):
                stripped = value.strip()
                if not stripped:
                    updates[field] = json.dumps([])
                    continue
                try:
                    parsed = json.loads(stripped)
                except json.JSONDecodeError:
                    parsed = [stripped]
            else:
                parsed = value
            if isinstance(parsed, (list, tuple, set)):
                normalized = [
                    str(item).strip()
                    for item in parsed
                    if item not in (None, "") and str(item).strip()
                ]
            else:
                normalized = [str(parsed).strip()] if str(
                    parsed).strip() else []
            updates[field] = json.dumps(normalized)
        Publication.objects.filter(pk=publication.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_publication"),
    ]

    operations = [
        migrations.RunPython(ensure_json_lists, noop_reverse),
        migrations.AlterField(
            model_name="publication",
            name="creator",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="publication",
            name="subject",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="publication",
            name="contributor",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="publication",
            name="identifier",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="publication",
            name="source",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="publication",
            name="language",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="publication",
            name="relation",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="publication",
            name="coverage",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
