# Generated by Django 5.2.8 on 2025-12-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_publication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publication',
            new_name='api_publica_slug_abb53e_idx',
            old_name='api_publicati_slug_8f026f_idx',
        ),
    ]
