# Generated by Django 5.2.8 on 2025-12-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_publication_multivalue_fields'),
        ('api', '0005_rename_api_publicati_slug_8f026f_idx_api_publica_slug_abb53e_idx'),
    ]

    operations = [
    ]
