# Generated by Django 5.2.8 on 2025-12-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_publicationmetadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publicationmetadata',
            new_name='api_publica_publica_655c47_idx',
            old_name='api_publica_public_30de68_idx',
        ),
        migrations.RenameIndex(
            model_name='publicationmetadata',
            new_name='api_publica_schema_d7b2c0_idx',
            old_name='api_publica_schema_0125f0_idx',
        ),
    ]
