# Generated by Django 5.2.8 on 2025-12-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_title_metadata'),
        ('api', '0008_rename_api_publica_public_30de68_idx_api_publica_publica_655c47_idx_and_more'),
    ]

    operations = [
    ]
