# Generated by Django 5.2.8 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20251211_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='oai_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
