# Generated by Django 5.2.8 on 2025-12-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_journal_oai_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_harvested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='publications', to='api.journal'),
        ),
        migrations.AddField(
            model_name='publication',
            name='oai_datestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='oai_identifier',
            field=models.CharField(
                blank=True, max_length=512, null=True, unique=True),
        ),
    ]
