# Generated by Django 6.0.3 on 2026-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_oaiharvestlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='researcherinstitutionalemailtoken',
            new_name='api_researc_token_6491b9_idx',
            old_name='api_research_token_9abf4f_idx',
        ),
        migrations.RenameIndex(
            model_name='researcherinstitutionalemailtoken',
            new_name='api_researc_profile_9de887_idx',
            old_name='api_research_profile__03fb7f_idx',
        ),
        migrations.AddField(
            model_name='publication',
            name='external_doi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='researcherexperience',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researcherinstitutionalemailtoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researcherpublication',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('invite', 'Invite'), ('reset', 'Password reset'), ('researcher_institutional', 'Researcher institutional email')], max_length=32),
        ),
    ]
